controller_list:
  - name: fake_ur5_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
      - link5_link6_joint
initial:  # Define initial robot poses per group
  - group: ur5_arm
    pose: home_position