arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_link1_joint
    - link1_link2_joint
    - link2_link3_joint
    - link3_link4_joint
    - link4_link5_joint
    - link5_link6_joint
  gains:
    base_link1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link1_link2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link2_link3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link3_link4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link4_link5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link5_link6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1