controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
      - link5_link6_joint