controller_joint_names: ['', 'base_link1_joint', 'link1_link2_joint', 'link2_link3_joint', 'link3_link4_joint', 'link4_link5_joint', 'link5_link6_joint', 'ee_left', 'ee_right', ]

ur5urdf: # change the name
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller 1
  joint_1_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: base_link1_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 2
  joint_2_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: link1_link2_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 3
  joint_3_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: link2_link3_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 4
  joint_4_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: link3_link4_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 5
  joint_5_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: link4_link5_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 6
  joint_6_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: link5_link6_joint # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 7
  joint_7_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: ee_left # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}

  # Controller 8
  joint_8_controller:
    type: effort_controllers/JointPositionController # Type of controller. 
    joint: ee_right # Name of the joint.  
    pid : {p: 1000.0 , i: 0.5 , d: 10} # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0}
